### ISSUE TITLE
A livery

### ISSUE THREAD

**Issue by randomgeofsplayer** [kolos26/GEOFS-LiverySelector#1]
https://ibb.co/g6hRhjS 

hope you can give it a shot!
if it doesn't work, feel free to DM me: coolpilot11#7155 

thanks-coolpilot

**Comment by kolos26** [comment]
I'm very happy to meet my first contributor! Thank you very much for contributing Livery Selector! :)
There were a few issues with your livery, but we can fix it easily.
- Your texture files size was too small, you will need to use 4096*4096. [Here](https://github.com/kolos26/GEOFS-LiverySelector/blob/main/maps/b737-700.png) is the correct map for you.
- Some parts of the texture file was also missing on your livery, but if you cut out the texts, and the engine, winglet and vertical stabilizer, it wont take a long time to fix.

You should send me the fixed version, I'm looking forward to put it into the official version.

**Comment by randomgeofsplayer** [comment]
working on adding those now! the ITA livery doesn't show up though, just saying.

**Comment by randomgeofsplayer** [comment]
![Untitled drawing (3) (1)](https://user-images.githubusercontent.com/99902452/185394536-34164848-6bc7-4460-bf96-cb60df329128.png)
It doesn't have the details, hope that's ok.

**Comment by kolos26** [comment]
I don't know what's the problem with your livery, somehow the top part of
the texture is missing, as you can see on the map I've sent you. I think
you should just copy paste the necessary parts of your painting to that
map. If you still have problems I will help you as soon as I can.

Never mind if the details are not 100% correct. If it's enough detailed for
you, I will add it anyway. This project is not about details, just about
making a community database, where everybody can share the liveries, and
use his favorites :).

I'm very happy because somebody is interested in tha ITA livery. I had some
problems during the tests of that livery, so I will need to work on that, I
have some ideas, but the a350-900 is a bit more complicated than I thought.

Thank you very much for your work, I'm sure that we will fix your livery
somehow.

randomgeofsplayer ***@***.***> ezt írta (időpont: 2022. aug.
18., Cs, 14:29):

**Comment by iuhairways** [comment]
I fixed it for you, idk if it'll work though
https://i.ibb.co/YTJc2dr/avelo.jpg

**Comment by iuhairways** [comment]
All cool on my end 
![image](https://user-images.githubusercontent.com/103064103/191103583-6c97d225-7211-4d0e-8279-5b409b54c654.png)

**Comment by kolos26** [comment]
Thank you, that's very kind of you
