### ISSUE TITLE
CRJ 200 issues 

### ISSUE THREAD

**Issue by Aero281** [kolos26/GEOFS-LiverySelector#610]
hi kolos its me aero281 the creator of the crj200, I've seen that your addon supports my crj200. But there's a problem.
as seen below the two dots are for the lights since the belavia livery had a grey bottom the dots were painted around the grey rectangle.
if you could you can change/modify all the liveries with appropriate colours for the rectangle 
![89](https://github.com/kolos26/GEOFS-LiverySelector/assets/87426088/fdd795d5-4ea3-450a-91d3-c02cd1741f98)
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/87426088/43ccb89a-a35d-4644-a7e5-33a459bbb221)

**Comment by kolos26** [comment]
Hi, It's a pleasure to meet you! Thank you for the tip, I will fix it on all the liveries. Best wishes Kolos

**Comment by scitor** [comment]
I'm sorry to takeover / necro this thread, but didn't want to create another one since I clarified with all the other authors already, only you @Aero281 I couldn't reach anywhere...  

It's about the CJR 200 and it's multiplayer model, as that has a different texture mapping than the main model, which is a slight problem described below.

LS is in the process of getting multiplayer functionality (ie others see your liveries) and most planes work already. Since LS only has textures for the main model, there are some restrictions for the multiplayer models, as thats what's getting the texture applied on the screen of other players:
- the UVs need to be the same for main and multiplayer.glb and 
- there should be either one single texture, or the same mapping as for the main model.

Currently the planes identified as incompatible will still keep their liveries (like it was before), they will just not be visible to other players.

Thanks for reading :)

**Comment by Aero281** [comment]
Hi I'm sorry but I've lost all the files of the crj200. If I could remember both the multiplayer and main model had the same texture with same mapping

**Comment by coolpilot11** [comment]
Hi Aero281. I'm reaching out regarding the airbus a340-300. I've got some ideas for how the handling could be improved, and I'd love to help implement them. Let me know if there's a way for me to reach you via the GeoFS wiki, discord, etc.

**Comment by Spice9** [comment]
@Aero281 Hi its seems like ur a340 has a lot of issues the main one being the model's size. Its smaller than an a350.The code needs to be revamped especially the physics part

**Comment by Spice9** [comment]
@Aero281 I've made changes to your a340 and improved a lot of things.You might want to use the code given below.
[aircraft.json](https://github.com/user-attachments/files/16558799/aircraft.json)

**Comment by Spice9** [comment]
@Aero281 I've made changes to your a340 and improved a lot of things.You might want to use the code given below.
[aircraft.json](https://github.com/user-attachments/files/16558929/aircraft.json)

**Comment by Spice9** [comment]
also this issue should be fixed as well 
![image](https://github.com/user-attachments/assets/e62d0b5b-8a5b-4536-9129-9a65344e5b88)

**Comment by Spice9** [comment]
@Aero281 the a340 suffers from severe understeer you migh want to increase the yaw value in nose suspension

**Comment by Spice9** [comment]
@Aero281 theres some issues regarding the a330-200 that u just released. I inspected the model and it seems like the fuselage and wings doesnt seem to have same material. It would be much recommended if you switch the material of you wing to material.004 as the winglets do not change liveries when using multiliveries/livery selector
